openapi: 3.0.2
info:
    title: Music-API
    version: 1.0.0
    description: '### This for Music API'
paths:
    /artists:
        get:
            tags:
                - artists
            responses:
                '200':
                    content:
                        Array of String as String:
                            schema:
                                $ref: '#/components/schemas/artist'
                            examples:
                                Artists:
                                    value: |-
                                        let data = [
                                            {id:1, name:"Alkem", country:"Estonia"}, 
                                            {id:2, name:"Jadeci", country:"USA"},
                                            {id:3, name:"Kanye West", country:"USA"},
                                            {id:4, name:"Island Boys", country:"USA"},
                                        ]
                    description: Return a list of artists.
            summary: Get a list of all Artists
            description: Returns a list of all artists.
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/artist'
                        examples:
                            NewArtist:
                                value:
                                    name: Jake Paul
                                    country: London
                required: true
            tags:
                - artists
            responses:
                '201':
                    headers:
                        location: {}
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/artist'
                            examples:
                                CreatedArtist:
                                    value:
                                        id: 3
                                        name: Jake Paul
                                        country: London
                    description: Success
            summary: Add a new Artist
    /songs:
        get:
            tags:
                - songs
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/song'
                            examples:
                                Example:
                                    value:
                                        id: 1
                                        name: Viva La Vida
                                        genre_id: 1
                                        date_published: 12-03-2023
                    description: song
            summary: Get a list of songs
            description: Returns a list of songs.
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/song'
                        examples:
                            NewArtist:
                                value:
                                    name: Jadeci
                                    country: USA
                                    genre_id: 1
                                    date_published: 12/03/2023
                required: true
            tags:
                - songs
            responses:
                '201':
                    headers:
                        location: {}
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/song'
                            examples:
                                CreatedArtist:
                                    value:
                                        id: 1
                                        name: Viva La Vida
                                        genre_id: 1
                                        date_published: 12-03-2023
                    description: Success
            summary: Add a new Song
    '/songs/{id}':
        get:
            tags:
                - songs
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                songs:
                                    value: |-
                                        let data = [
                                            {id:1, name:"Viva La Vida", genre_id:1, date_published:Date(20/12/2022)}, 
                                            {id:2, name:"In the end", genre_id:1, date_published:Date(20/12/2022)},
                                            {id:3, name:"Daylight", genre_id:1, date_published:Date(20/12/2022)},
                                            {id:4, name:"Megalovania", genre_id:1, date_published:Date(20/12/2022)},
                                        ]
                    description: Succesful
                '404':
                    description: Song not found.
            operationId: id
            summary: Get by Id
            description: Return all details of artists by Id.
        put:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/song'
                        examples:
                            Updated Song:
                                value:
                                    id: 32
                                    name: Rap god
                                    date_published: 12-03-2023
                                    genre_id: 1
                required: true
            tags:
                - songs
            responses:
                '204':
                    headers:
                        Location:
                            schema:
                                type: string
                    description: Success
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                error:
                                    value:
                                        error: Song not found
                    description: Success
            summary: Update by Id
        delete:
            tags:
                - songs
            responses:
                '204':
                    description: Succeeded
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                NotFound:
                                    value:
                                        error: Song not found
                    description: Song not found
            summary: Delete by Id
        parameters:
            -
                name: id
                in: path
                required: true
    '/artists/{id}':
        get:
            tags:
                - artists
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                artists:
                                    value: |-
                                        let data = [
                                            {id:1, name:"Alkem", country:"Estonia"}, 
                                            {id:2, name:"Jadeci", country:"USA"},
                                            {id:3, name:"Kanye West", country:"USA"},
                                            {id:4, name:"Island Boys", country:"USA"},
                                        ]
                    description: Succesful
                '404':
                    description: Artist not found.
            operationId: id
            summary: Get by Id
            description: Return all details of artists by Id.
        put:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/artist'
                        examples:
                            Updated artist:
                                value:
                                    id: 40
                                    name: Eminem2
                                    country: South Africa
                required: true
            tags:
                - artists
            parameters:
                -
                    name: id
                    schema:
                        type: integer
                    in: path
                    required: true
            responses:
                '204':
                    headers:
                        location:
                            schema:
                                type: string
                    description: Success
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Not found:
                                    value:
                                        error: artist not found
                    description: Not found
            summary: Update by Id
        delete:
            tags:
                - artists
            responses:
                '204':
                    description: Succeeded
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                NotFound:
                                    value:
                                        error: Artist not found
                    description: Artist not found
            summary: Delete by Id
        parameters:
            -
                name: id
                in: path
                required: true
components:
    schemas:
        error:
            title: Root Type for error
            description: 'Error, did not find artist.'
            type: object
            properties:
                error:
                    type: string
            example:
                error: Error message.
        artist:
            title: Root Type for artist
            description: ''
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                country:
                    type: string
            example:
                id: 4
                name: Island Boys
                country: USA
        song:
            description: ''
            type: object
            example: |-
                let data = [
                    {id:1, genre_id:"0", name:"Gangnam style", date_published:Date(1/2/2022)}, 
                    {id:2, genre_id:"0", name:"song", date_published:Date(20/12/2022)}, 
                ]
